src/main/java/lottery/model/Nurse.java
package lottery.model;

import javax.persistence.*;
import java.io.Serializable;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * class description of Nurse
 *
 * @author johnson
 */
//@Entity
//@Table(name = "nurse")
public class Nurse implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Integer id;

    @Column(unique = true)
    private String no;

    private String name;

    @Column(name = "updatetime", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    private Date updatetime;

    @PrePersist
    @PreUpdate
    void beforePersist() {
        this.updatetime = new Date();
    }

    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(name = "station_nurse",
            joinColumns = {
                @JoinColumn(name = "nurse_id", referencedColumnName = "id")},
            inverseJoinColumns = {
                @JoinColumn(name = "station_id", referencedColumnName = "id")})
    private Set<Station> stations = new HashSet<>(0);

    @Transient
    private Date addStationTime;

    public Nurse() {
    }

    public Nurse(String no, String name) {
        this.no = no;
        this.name = name;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getNo() {
        return no;
    }

    public void setNo(String no) {
        this.no = no;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getUpdatetime() {
        return updatetime;
    }

    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    public String getUpdatetimeFormated() {
        return DateTimeFormatter.ISO_DATE_TIME.format(
                LocalDateTime.ofInstant(getUpdatetime().toInstant(), ZoneId.systemDefault())
        );
    }

    public Set<Station> getStations() {
        return stations;
    }

    public void setStations(Set<Station> stations) {
        this.stations = stations;
    }

    public Date getAddStationTime() {
        return addStationTime;
    }

    public String getAddStationTimeFormated() {
        return DateTimeFormatter.ISO_DATE_TIME.format(
                LocalDateTime.ofInstant(getAddStationTime().toInstant(), ZoneId.systemDefault())
        );
    }

    public void setAddStationTime(Date addStationTime) {
        this.addStationTime = addStationTime;
    }
}

src/main/webapp/WEB-INF/views/index.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<html>
<head>
    <meta charset="utf-8">
    <title>index</title>

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href='<spring:url value="/resources/bootstrap/css/bootstrap.min.css"/>'>
    <link rel="stylesheet" href='<spring:url value="/resources/bootstrap/css/bootstrap-theme.min.css"/>'>
</head>
<body>
    <div class="container theme-showcase"id="main">
        <ul>
            <li>
                <span>
                    <button type="button" class="btn btn-lg btn-link">
                        <a href='<spring:url value="/station/new"/>'>新增站點</a>
                    </button>
                </span>
            </li>
            <li>
                <span>
                    <button type="button" class="btn btn-lg btn-link">
                        <a href='<spring:url value="/station/list"/>'>站點列表</a>
                    </button>
                </span>
            </li>
            <li>
                <span>
                    <button type="button" class="btn btn-lg btn-link">
                        <a href='<spring:url value="/nurse/new"/>'>新增護士</a>
                    </button>
                </span>
            </li>
            <li>
                <span>
                    <button type="button" class="btn btn-lg btn-link">
                        <a href='<spring:url value="/nurse/list"/>'>護士列表</a>
                    </button>
                </span>
            </li>
        </ul>
    </div>
    <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
    <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src='<spring:url value="/resources/bootstrap/js/bootstrap.min.js"/>'></script>
</body>
</html>

src/main/webapp/WEB-INF/views/listNurse.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<html>
<head>
    <title>list nurse</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href='<spring:url value="/resources/bootstrap/css/bootstrap.min.css"/>'>
    <link rel="stylesheet" href='<spring:url value="/resources/bootstrap/css/bootstrap-theme.min.css"/>'>
</head>
<body>
<div id="function">
        <span>
            <button value="返回" id="returnBtn">返回</button>
        </span>
</div>
<c:if test="${not empty message}">
<div class="message">
    ${message.messageString}
</div>
</c:if>
<div id="stationListTable" class="col-md-6">
    <c:if test="${not empty nurseList}">
        <table class="table table-striped">
            <thead>
            <tr>
                <th>員編</th>
                <th>修改時間</th>
                <th>動作</th>
            </tr>
            </thead>
            <tbody>
            <c:forEach items="${nurseList}" var="nurse">
                <tr>
                    <td>${nurse.no}</td>
                    <td>${nurse.updatetimeFormated}</td>
                    <td>
                        <span>
                            <a href='<spring:url value="/nurse/view/${nurse.id}"/>'>View</a>
                        </span>
                        <span>
                            <a href="#" class="delNurseLink" rel="${nurse.id}">Del</a>
                        </span>
                    </td>
                </tr>
            </c:forEach>
            </tbody>
        </table>
    </c:if>
    <c:if test="${empty nurseList}">
        <div class="alert alert-warning" role="alert">
            <spring:message code="noNusre"/>
        </div>
    </c:if>
</div>

<script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
<script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<script src='<spring:url value="/resources/bootstrap/js/bootstrap.min.js"/>'></script>

<script>
    $(function () {
        $('#returnBtn').click(function () {
            window.location = '<spring:url value="/"/>';
        });

        $('.delNurseLink').click(function () {
            if (window.confirm('<spring:message code="confirmMsg"/>')) {
                $.post(
                        '<spring:url value="/nurse/delete/"/>/' + $(this).attr("rel"),
                        function () {
                            window.location.replace('<spring:url value="/nurse/list"/>');
                        }
                );
            }
        });
    });
</script>
</body>
</html>

src/main/webapp/WEB-INF/views/listStation.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<html>
<head>
    <title>list station</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href='<spring:url value="/resources/bootstrap/css/bootstrap.min.css"/>'>
    <link rel="stylesheet" href='<spring:url value="/resources/bootstrap/css/bootstrap-theme.min.css"/>'>
</head>
<body>
    <div id="function">
        <span>
            <button value="返回" id="returnBtn">返回</button>
        </span>
    </div>
    <div id="stationListTable" class="col-md-6">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>站點</th>
                    <th>修改時間</th>
                    <th>動作</th>
                </tr>
            </thead>
            <tbody>
            <c:forEach items="${stationList}" var="station">
                <tr>
                    <td>${station.name}</td>
                    <td>${station.updatetimeFormated}</td>
                    <td>
                        <span>
                            <a href='<spring:url value="/station/view/${station.id}"/>'>View</a>
                        </span>
                        <span>
                            <a href="#" class="delStationLink" rel="${station.id}">Del</a>
                        </span>
                    </td>
                </tr>
            </c:forEach>
            </tbody>
        </table>
    </div>

    <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
    <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src='<spring:url value="/resources/bootstrap/js/bootstrap.min.js"/>'></script>

    <script>
        $(function() {
            $('#returnBtn').click(function() {
                window.location = '<spring:url value="/"/>';
            });

            $('.delStationLink').click(function() {
                if(window.confirm('<spring:message code="confirmMsg"/>')) {
                    $.post('<spring:url value="/station/delete/"/>/'+$(this).attr("rel"), function() {
                        window.location.replace('<spring:url value="/station/list"/>');
                    });
                }
            });
        });
    </script>
</body>
</html>

src/main/webapp/WEB-INF/views/newNurse.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<html>
<head>
    <title>new nurse</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href='<spring:url value="/resources/bootstrap/css/bootstrap.min.css"/>'>
    <link rel="stylesheet" href='<spring:url value="/resources/bootstrap/css/bootstrap-theme.min.css"/>'>
    <link rel="stylesheet" media="screen" type="text/css" href='<c:url value="/resources/multiselect/css/multi-select.css"/>'>
</head>
<body>
    <div id="function">
        <span>
            <button value="返回" id="returnBtn">返回</button>
        </span>
        <span>
            <button value="新增" id="confirmBtn">新增</button>
        </span>
    </div>
    <form id="form" method="post" action='<spring:url value="/nurse/new"/>'>
        <div id="nurseContent">
            <label for="no">員工編號</label>
            <input id="no" name="no" type="text" size="10" maxlength="10">
            <br/>
            <label for="name">護士姓名</label>
            <input id="name" name="name" type="text" size="10" maxlength="10">
        </div>
        <div id="stationSelection" class="col-md-6">
            <c:if test="${not empty stationList}">
                <div class="panel panel-success">
                    <div class="panel-heading">
                        <h3 class="panel-title">分配站點</h3>
                    </div>
                    <div class="panel-body">
                        直接點選項目做加入/移除
                    </div>
                </div>
                <select multiple="multiple" id="stationSelect" name="stationSelect">
                    <c:forEach items="${stationList}" var="station">
                        <option value="${station.id}">${station.name}</option>
                    </c:forEach>
                </select>
            </c:if>
            <c:if test="${empty stationList}">
                <div class="alert alert-warning" role="alert">
                    <spring:message code="noStation"/>
                </div>
            </c:if>
        </div>
    </form>

    <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
    <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src='<spring:url value="/resources/bootstrap/js/bootstrap.min.js"/>'></script>
    <script src='<c:url value="/resources/multiselect/js/jquery.multi-select.js"/>'></script>

    <script>
        $(function() {
            $('#confirmBtn').click(function() {
                $('#form').submit();
            });
            $('#returnBtn').click(function() {
                window.location = '<spring:url value="/"/>';
            });
            <c:if test="${not empty stationList}">
            $('#stationSelect').multiSelect({
                keepOrder: true,
                selectableHeader: "<div class='custom-header'>未加入</div>",
                selectionHeader: "<div class='custom-header'>加入</div>"
            });
            </c:if>
        });
    </script>
</body>
</html>

src/main/webapp/WEB-INF/views/newStation.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<html>
<head>
    <title>new station</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href='<spring:url value="/resources/bootstrap/css/bootstrap.min.css"/>'>
    <link rel="stylesheet" href='<spring:url value="/resources/bootstrap/css/bootstrap-theme.min.css"/>'>
</head>
<body>
    <div id="function">
        <span>
            <button value="返回" id="returnBtn">返回</button>
        </span>
        <span>
            <button value="新增" id="confirmBtn">新增</button>
        </span>
    </div>
    <div id="stationContent" class="col-md-6">
        <form id="form" method="post" action='<spring:url value="/station/new"/>'>
            <label for="stationName">站點名稱</label>
            <input id="stationName" name="stationName" type="text" size="10" maxlength="10">
        </form>
    </div>

    <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
    <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src='<spring:url value="/resources/bootstrap/js/bootstrap.min.js"/>'></script>

    <script>
        $(function() {
            $('#confirmBtn').click(function() {
                $('#form').submit();
            });
            $('#returnBtn').click(function() {
                window.location = '<spring:url value="/"/>';
            });
        });
    </script>
</body>
</html>

src/main/webapp/WEB-INF/views/viewNurse.jsp
<%@ page import="java.util.Set" %>
<%@ page import="java.util.List" %>
<%@ page import="lottery.model.Station" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<html>
<head>
    <title>view nurse</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href='<spring:url value="/resources/bootstrap/css/bootstrap.min.css"/>'>
    <link rel="stylesheet" href='<spring:url value="/resources/bootstrap/css/bootstrap-theme.min.css"/>'>
    <link rel="stylesheet" media="screen" type="text/css" href='<c:url value="/resources/multiselect/css/multi-select.css"/>'>
</head>
<body>
    <div id="function">
        <span>
            <button value="返回" id="returnBtn">返回</button>
        </span>
        <span>
            <button value="新增" id="updateBtn">儲存</button>
        </span>
    </div>
    <form id="form" method="post" action='<spring:url value="/nurse/update/${nurse.id}"/>'>
        <div id="stationContent">
            <label for="no">員工編號</label>
            <input id="no" name="no" type="text" size="10" maxlength="10" value='${nurse.no}'>
            <br/>
            <label for="name">護士姓名</label>
            <input id="name" name="name" type="text" size="10" maxlength="10" value='${nurse.name}'>
        </div>
        <div id="stationSelection" class="col-md-6">
            <div class="panel panel-success">
                <div class="panel-heading">
                    <h3 class="panel-title">分配站點</h3>
                </div>
                <div class="panel-body">
                    直接點選項目做加入/移除
                </div>
            </div>
            <%--<span>分配站點：直接點選項目做加入/移除</span>--%>
            <select multiple="multiple" id="stationSelect" name="stationSelect">
            <%
                List<Station> stationList = (List<Station>) request.getAttribute("stationList");
                Set<Integer> nurseStationsId = (Set<Integer>) request.getAttribute("nurseStationsId");
                for (Station station : stationList) {
                    if (nurseStationsId.contains(station.getId())) {
            %>
                <option value="<%=station.getId() %>" selected><%=station.getName() %>
                </option>
                <%
                } else {
                %>
                <option value="<%=station.getId() %>"><%=station.getName() %>
                </option>
                <%
                        }
                    }
            %>
            </select>
        </div>
    </form>

    <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
    <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src='<c:url value="/resources/multiselect/js/jquery.multi-select.js"/>'></script>
    <script src='<spring:url value="/resources/bootstrap/js/bootstrap.min.js"/>'></script>

    <script>
        $(function() {
            $('#updateBtn').click(function() {
                $('#form').submit();
            });
            $('#returnBtn').click(function() {
                window.location = '<spring:url value="/nurse/list"/>';
            });
            $('#stationSelect').multiSelect({
                keepOrder: true,
                selectableHeader: "<div class='custom-header'>未加入</div>",
                selectionHeader: "<div class='custom-header'>已加入</div>"
            });
        });
    </script>
</body>
</html>

src/main/webapp/WEB-INF/views/viewStation.jsp
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<html>
<head>
    <title>view station</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href='<spring:url value="/resources/bootstrap/css/bootstrap.min.css"/>'>
    <link rel="stylesheet" href='<spring:url value="/resources/bootstrap/css/bootstrap-theme.min.css"/>'>
</head>
<body>
    <div id="function">
        <span>
            <button value="返回" id="returnBtn">返回</button>
        </span>
        <span>
            <button value="新增" id="updateBtn">儲存</button>
        </span>
    </div>
    <div id="stationContent">
        <form id="form" method="post" action='<spring:url value="/station/update/${station.id}"/>'>
            <label for="stationName">站點名稱</label>
            <input id="stationName" name="stationName" type="text" size="10" maxlength="10" value='${station.name}'>
        </form>
    </div>
    <div id="nurseList" class="col-md-6">
        <span>站點護士列表(test)</span>
        <c:if test="${not empty station.nurses}">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>員工編號</th>
                    <th>加入時間</th>
                </tr>
                </thead>
                <tbody>
                <c:forEach items="${station.nurses}" var="nurse">
                    <tr>
                        <td>${nurse.no}</td>
                        <td>${nurse.addStationTimeFormated}</td>
                    </tr>
                </c:forEach>
                </tbody>
            </table>
        </c:if>
        <c:if test="${empty station.nurses}">
            <span>
                <spring:message code="noNurseIn"/>
            </span>
        </c:if>
    </div>

    <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
    <script src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script src='<spring:url value="/resources/bootstrap/js/bootstrap.min.js"/>'></script>

    <script>
        $(function() {
            $('#updateBtn').click(function() {
                $('#form').submit();
            });
            $('#returnBtn').click(function() {
                window.location = '<spring:url value="/station/list"/>';
            });
        });
    </script>
</body>
</html>